= programming challenge

== Getting started

=== Getting a copy
The starting point for every challenge is provided as a branch in a Gitlab.com/GitHub
hosted Git repository. Be careful to adjust the URLs below
accordingly.

To start

=== Fork or directly clone the repository

```
git clone https://[gitlab|github].com/exxcellent/programming-challenge.git
```
or if you've forked the repository then
```
git clone git@[gitlab|github].com:YOURNAME/programming-challenge.git
```

See what challenges are available by listing the branches present:
```
git branch -a
```

=== Switch to the branch of the challenge assigned
```
cd programming-challenge
git checkout challenge-CHALLENGENAME
```

=== Building and running
The project scaffolds provides a Maven `pom.xml` as starting
point. You should be able to start with any IDE or text editor
you are convenient with.

After installing Maven 3.x you should be able to

Build & test your project::
    `mvn verify`

Then to run the main class _de.exxcellent.challenge.App_::
    `mvn exec:java`

To remove the compilation output::
    `mvn clean`

Or use your IDE functionality::
    to run & debug you program.
